# Generated by Django 4.1.2 on 2022-10-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='10.0.0.0')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
